### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by anselb** [C3NZ/CS22#3]
I think your graphs code is pretty good at the moment. Don't feel like you need to change anything I mention about your code.

### Readability and Formatting
- Your code is very readable. I think it reaches "Mastery" for each point in this category on the [Code Rubric](https://docs.google.com/document/d/19m8J8I5ZT66m5x1Q87yr6-CDg_jxBNCVd_a4fSq1xiw/preview).
- Your doc strings are great as well. I appreciate your labelling of everything with a simple summary, the arguments, and the return values. I feel like my linter would bug me for not have a period to end the first line of the doc string, but I definitely don't think it's necessary.

### Organization and Modularity
- I like how you separated your code into the main graph file, the vertex file, and the digraph file. While I did not separate the vertex and graph class, I do think the separation helps indicate the different classes, and makes the code overall more readable with smaller file sizes.
- While you do separate a directed and undirected graph, a weighted and unweighted graph are not that different with your implementation. In my code, I added a `weighted` graph property, and changed how some functions would work if that property was `True` or `False`. For example, when getting the edge of a graph, I decided to hide the edges, and when someone added a weighted edge to the unweighted graph, I would let them know that the graph was unweighted. I just wanted to make sure the user was aware of what type of graph they were working with, so they would not accidentally do something or get the wrong idea.

### Standard Library/Conventions
- I like how you take advantage of the builtin `deque` and `PriorityQueue`. I think you take advantage of the standard library to the fullest extent possible.
- It appears that you're using the PEP8 style guide; your code is definitely "Pythonic".

### Effectiveness of Solution
- I think your code for the graph are great solutions to the challenge and tutorial prompts. They seem to handle all necessary typical cases and edge cases.

### Testing and Error Handling
- Your tests seem to cover all of the typical cases, and most of the edge cases. The few edge cases I thought were missing are pretty edgy, so you don't need to worry about them.
- It would be nice to see more tests for error cases. You have a lot of error handling in your methods, but not all of it gets tested by your tests.

### Algorithmic Complexity
- I was wondering why you decided to store the vertex neighbors and weights as a list of tuples rather than a dictionary in your `Vertex` class. It seems you set up the `__hash__` and `__eq__` methods to be able to hash the `Vertex` class when using it as a key in a dictionary. This doesn't seem to matter much though. Most cases need to iterate through all the neighbors, and the only case where it doesn't need to is when it checks if a vertex is already neighbor.
- As far as I can tell, your search algorithms seem to have optimal runtime complexities.

**Comment by vmarcella** [comment]
Thank you for the very constructive feedback. I appreciate it and will use this for future solutions to the challenges!
